name: MessageBlocker
version: 1.0.2
api-version: 1.13
main: software.krymo.minecraft.spigot.message_blocker.MessageBlocker
description: Block annoying chat messages from the Minecraft vanilla server, plugins or players.
author: Krymonota
website: https://github.com/Krymonota/message-blocker
